package app.tek4tv.digitalsignage.utils

object Status {
    const val CAPTURE_SCREEN = "CAPTURE_SCREEN"
    const val SET_MUTE_PLAYER = "SET_MUTE_PLAYER"
    const val GET_LIST = "GET_LIST"
    const val UPDATE_LIST = "UPDATE_LIST"
    const val NEXT = "NEXT"
    const val PREVIEW = "PREVIEW"
    const val JUMP = "JUMP"
    const val LIVE = "LIVE"
    const val UPDATE_STATUS = "UPDATE_STATUS"
    const val SET_VOLUME = "SET_VOLUME"
    const val SET_VOLUME_DEVICE = "SET_VOLUME_DEVICE"
    const val STOP = "STOP"
    const val PAUSE = "PAUSE"
    const val START = "START"
    const val RESTART = "RESTART"
    const val RELOAD = "RELOAD"
    const val SET_MUTE_DEVICE = "SET_MUTE_DEVICE"
    const val SWITCH_MODE_FM = "SWITCH_MODE_FM"
    const val GET_VOLUME_DEVICE = "GET_VOLUME_DEVICE"
    const val GET_SOURCE_AUDIO = "GET_SOURCE_AUDIO"
    const val GET_PA = "GET_PA"
    const val GET_FM_FQ = "GET_FM_FQ"
    const val GET_AM_FQ = "GET_AM_FQ"
    const val GET_TEMPERATURE = "GET_TEMPERATURE"
    const val GET_LOCATION = "GET_LOCATION"
    const val UPDATE_VERSION = "UPDATE_VERSION"
    const val UPDATE_MUSIC = "UPDATE_MUSIC"
    const val PONG = "PONG"
    const val ROTATION = "ROTATION"
    const val SET_TIME_OVER = "SET_TIME_OVER"
    const val SET_TIME_ON = "SET_TIME_ON"
    const val GET_APP_VERSION = "GET_APP_VERSION"
    const val DTMF_STATUS = "DTMF_STATUS"
    const val NETWORK_INFO = "NETWORK_INFO"
    const val STORAGE_INFO = "STORAGE_INFO"
    const val GET_AUDIO_PATH = "GET_AUDIO_PATH"
    const val GET_MEDIA_PATH = "GET_MEDIA_PATH"
    const val DELETE_ALL_AUDIO = "DELETE_ALL_AUDIO"
    const val DELETE_ALL_MEDIA = "DELETE_ALL_MEDIA"
}