/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_app_tek4tv_digitalsignage_SerialPort
#define _Included_app_tek4tv_digitalsignage_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_app_tek4tv_digitalsignage_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_app_tek4tv_digitalsignage_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
